services:
  auth-10-service:    
    container_name: collection-10-service
    build:
      context: .
      dockerfile: src/Dockerfile
    env_file:
      - ./src/.env
    ports:
      - "5012:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development     
    volumes:
      - ./src/dataprotection-keys:/home/app/.aspnet/DataProtection-Keys  
    networks:
      - tom-auth-net
      
networks:
  tom-auth-net:
    driver: bridge